name: Push to PR

on:
  push:
    branches:
      - "design-token"

jobs:
  build-rn-token:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.ACCESS_TOKEN}}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: build project
        run: yarn build

      - name: commit and push new changes to design-token branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 토큰 빌드 결과물 업데이트"

      - uses: actions/checkout@v4
      - name: create pull request
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ezllabsChoiYeongho/github-actions-practice/pulls \
          -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"design-token","base":"main"}'

  # create-pull-request:
  #   runs-on: ubuntu-latest
  #   needs: build-rn-token
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: create pull request
  #       run: |
  #         curl -L \
  #         -X POST \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
  #         -H "X-GitHub-Api-Version: 2022-11-28" \
  #         https://api.github.com/repos/ezllabsChoiYeongho/github-actions-practice/pulls \
  #         -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"design-token","base":"main"}'
