name: Push to PR

on:
  push:
    branches:
      - "design-token"

permissions: write-all

jobs:
  build-rn-token:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: build project
        run: yarn build

      - name: commit and push new changes to design-token branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 토큰 빌드 결과물 업데이트"

  create-pull-request:
    runs-on: ubuntu-latest
    needs: build-rn-token
    steps:
      - uses: actions/checkout@v4
      - name: create pull request
        run: gh pr create -B main -H design-token --title "테스트 PR" --body "테스트 PR for Token Studio"
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
