name: Push to PR

on:
  push:
    branches:
      - "design-token"

jobs:
  push-to-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: make pr to main using REST_API
        run: echo "${{secrets.GITHUB_TOKEN}}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: make pr to main using REST_API
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ezllabsChoiYeongho/github-actions-practice/pulls \
          -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"design-token","base":"main"}'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
